apiVersion: v1
kind: Pod
metadata:
  name: dns-test
  namespace: hslu-app-hybrid
spec:
  containers:
  - name: dnstools
    image: infoblox/dnstools:latest
    command: ["sleep", "3600"]
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
  restartPolicy: Never