apiVersion: v1
kind: Pod
metadata:
  name: psql-test
  namespace: hslu-app-hybrid
spec:
  containers:
  - name: psql
    image: bitnami/postgresql:latest
    command: ["sleep", "3600"]
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
  restartPolicy: Never